const jobs_data = [
  {
    "job_name": "Automation Engineer",
    "company_name": "Ericsson",
    "location": "Noida",
    "qualification": "Bachelor's degree or MCA",
    "apply_link": "https://www.ericsson.com/careers",
    "salary": "₹6,00,000 - ₹8,00,000 per year",
    "description": "As an Automation Engineer, you will be responsible for building and maintaining test frameworks, automating software tests, and enhancing efficiency.",
  },
  {
    "job_name": "Tax Analyst",
    "company_name": "Datamatics Business Solutions Ltd",
    "location": "Mumbai",
    "qualification": "Various",
    "apply_link": "https://www.datamatics.com/careers",
    "salary": "₹4,50,000 - ₹6,00,000 per year",
    "description": "A Tax Analyst at Datamatics handles tax-related issues, ensuring compliance with the latest tax regulations and managing financial reporting.",
  },
  {
    "job_name": "MIS Officer",
    "company_name": "HDB Financial Services",
    "location": "Coimbatore",
    "qualification": "Graduate/Post Graduate",
    "apply_link": "https://www.hdbfs.com/careers",
    "salary": "₹5,00,000 per year",
    "description": "The MIS Officer will be responsible for managing data and providing reports to facilitate informed decision-making.",
  },
  {
    "job_name": "Non Voice Associate",
    "company_name": "NTT DATA",
    "location": "Chennai",
    "qualification": "Various",
    "apply_link": "https://www.nttdata.com/careers",
    "salary": "₹3,00,000 per year",
    "description": "The Non-Voice Associate will handle customer service tasks through email, chat, and other non-voice mediums.",
  },
  {
    "job_name": "HR Trainee",
    "company_name": "Soft Suave",
    "location": "Chennai",
    "qualification": "Any Graduate",
    "apply_link": "https://www.softsuave.com/career",
    "salary": "₹2,50,000 per year",
    "description": "The HR Trainee will assist in recruitment, payroll, employee relations, and other HR functions.",
  },
  {
    "job_name": "Customer Support Executive",
    "company_name": "Teleperformance",
    "location": "Bangalore",
    "qualification": "Any Graduate",
    "apply_link": "https://www.teleperformance.com/careers",
    "salary": "₹3,00,000 per year",
    "description": "Customer Support Executives are responsible for managing customer inquiries and providing solutions to their issues.",
  },
  {
    "job_name": "Software Development Engineer Intern (SDE I)",
    "company_name": "Amazon",
    "location": "Multiple locations in India (Bangalore, Hyderabad, Pune, Delhi, Chennai, Mumbai)",
    "qualification": "Bachelor's degree",
    "apply_link": "https://www.amazon.jobs",
    "salary": "₹7,00,000 per year",
    "description": "As a Software Development Engineer Intern, you will be working on software design, implementation, and testing.",
  },
  {
    "job_name": "Graduate Engineer Trainee",
    "company_name": "Koch Industries",
    "location": "Bangalore",
    "qualification": "B.E/B.Tech",
    "apply_link": "https://www.kochind.com/careers",
    "salary": "₹5,50,000 per year",
    "description": "Graduate Engineer Trainees will engage in engineering activities including project management, process optimization, and software development.",
  },
  {
    "job_name": "QA Engineer",
    "company_name": "Motive",
    "location": "India (Remote)",
    "qualification": "Various",
    "apply_link": "https://www.motive.com/careers",
    "salary": "₹6,00,000 per year",
    "description": "QA Engineers at Motive ensure the quality of products by developing and executing tests, identifying bugs, and improving software products.",
  },
  {
    "job_name": "Data Scientist",
    "company_name": "Visa",
    "location": "Bengaluru (Remote)",
    "qualification": "Various",
    "apply_link": "https://www.visa.com/careers",
    "salary": "₹10,00,000 per year",
    "description": "The Data Scientist will analyze large datasets to create models, identify trends, and derive actionable insights.",
  },
  {
    "job_name": "Backend Developer",
    "company_name": "Tata Consultancy Services",
    "location": "Pune",
    "qualification": "B.Tech in Computer Science",
    "apply_link": "https://www.tcs.com/careers",
    "salary": "₹7,50,000 per year",
    "description": "TCS is hiring a Backend Developer who will be responsible for designing and implementing server-side logic, databases, and API integration.",
  },
  {
    "job_name": "Full Stack Developer",
    "company_name": "Cognizant",
    "location": "Chennai",
    "qualification": "B.Tech/M.Tech in Computer Science",
    "apply_link": "https://www.cognizant.com/careers",
    "salary": "₹8,00,000 per year",
    "description": "The Full Stack Developer will work on both front-end and back-end development, handling the full lifecycle of software applications.",
  },
  {
    "job_name": "Product Manager",
    "company_name": "Flipkart",
    "location": "Bangalore",
    "qualification": "MBA, B.Tech",
    "apply_link": "https://www.flipkart.com/careers",
    "salary": "₹15,00,000 per year",
    "description": "The Product Manager will lead the development of new products and features, collaborate with engineering, marketing, and design teams.",
  },
  {
    "job_name": "Business Analyst",
    "company_name": "Accenture",
    "location": "Hyderabad",
    "qualification": "BBA/MBA in Business Analytics or related field",
    "apply_link": "https://www.accenture.com/careers",
    "salary": "₹6,50,000 per year",
    "description": "The Business Analyst will analyze business requirements, create reports, and optimize business processes to enhance efficiency and profitability.",
  },
  {
    "job_name": "UX/UI Designer",
    "company_name": "Wipro",
    "location": "Bangalore",
    "qualification": "B.Des or B.Tech in related fields",
    "apply_link": "https://www.wipro.com/careers",
    "salary": "₹7,00,000 per year",
    "description": "As a UX/UI Designer at Wipro, you'll be responsible for designing seamless and user-friendly interfaces for software applications.",
  },
  {
    "job_name": "Cloud Engineer",
    "company_name": "Microsoft",
    "location": "Hyderabad",
    "qualification": "B.Tech in Computer Science or related field",
    "apply_link": "https://careers.microsoft.com",
    "salary": "₹12,00,000 per year",
    "description": "Cloud Engineers at Microsoft work to design, implement, and manage cloud infrastructure, focusing on scalability and security.",
  },
  {
    "job_name": "DevOps Engineer",
    "company_name": "IBM",
    "location": "Bangalore",
    "qualification": "B.Tech in Computer Science",
    "apply_link": "https://www.ibm.com/careers",
    "salary": "₹9,00,000 per year",
    "description": "As a DevOps Engineer, you will focus on automating infrastructure and managing deployment pipelines to ensure smooth operations.",
  },
  {
    "job_name": "Data Engineer",
    "company_name": "Infosys",
    "location": "Bangalore",
    "qualification": "B.Tech in Computer Science or related field",
    "apply_link": "https://www.infosys.com/careers",
    "salary": "₹8,00,000 per year",
    "description": "Data Engineers at Infosys design and maintain data pipelines, integrate data from multiple sources, and ensure data quality.",
  },
  {
    "job_name": "Digital Marketing Specialist",
    "company_name": "Zomato",
    "location": "Gurgaon",
    "qualification": "Bachelor's degree in Marketing or related field",
    "apply_link": "https://www.zomato.com/careers",
    "salary": "₹5,00,000 per year",
    "description": "The Digital Marketing Specialist will manage online marketing campaigns, SEO, and social media strategies to increase brand visibility.",
  },
  {
    "job_name": "Network Engineer",
    "company_name": "Cisco",
    "location": "Chennai",
    "qualification": "B.Tech in Computer Science or Networking",
    "apply_link": "https://www.cisco.com/careers",
    "salary": "₹7,00,000 per year",
    "description": "Network Engineers at Cisco are responsible for maintaining, designing, and troubleshooting network infrastructures to ensure smooth connectivity.",
  },
  {
    "job_name": "AI Research Scientist",
    "company_name": "Google",
    "location": "Bangalore",
    "qualification": "M.Tech/PhD in Computer Science or related fields",
    "apply_link": "https://careers.google.com",
    "salary": "₹18,00,000 per year",
    "description": "The AI Research Scientist will work on developing cutting-edge machine learning models and AI technologies.",
  },
  {
    "job_name": "Java Developer",
    "company_name": "Tech Mahindra",
    "location": "Pune",
    "qualification": "B.Tech in Computer Science",
    "apply_link": "https://www.techmahindra.com/careers",
    "salary": "₹6,50,000 per year",
    "description": "A Java Developer at Tech Mahindra will design, implement, and maintain Java applications.",
  },
  {
    "job_name": "Software Engineer (Mobile)",
    "company_name": "Amazon",
    "location": "Hyderabad",
    "qualification": "B.Tech/M.Tech in Computer Science",
    "apply_link": "https://www.amazon.jobs",
    "salary": "₹10,00,000 per year",
    "description": "Software Engineer specializing in mobile technologies to build scalable and user-friendly mobile apps.",
  },
  {
    "job_name": "Frontend Developer",
    "company_name": "Adobe",
    "location": "Bangalore",
    "qualification": "B.Tech in Computer Science or equivalent",
    "apply_link": "https://www.adobe.com/careers",
    "salary": "₹9,00,000 per year",
    "description": "Adobe is hiring a frontend developer for creating responsive and dynamic user interfaces for web applications.",
  },
  {
    "job_name": "Cybersecurity Analyst",
    "company_name": "Dell Technologies",
    "location": "Chennai",
    "qualification": "B.Tech in Cybersecurity or IT",
    "apply_link": "https://www.dell.com/careers",
    "salary": "₹12,00,000 per year",
    "description": "Responsible for protecting Dell's IT infrastructure from cyber threats, ensuring data security across all platforms.",
  },
  {
    "job_name": "Data Analyst",
    "company_name": "Paytm",
    "location": "Noida",
    "qualification": "B.Tech in Computer Science, Data Science, or related field",
    "apply_link": "https://www.paytm.com/careers",
    "salary": "₹6,00,000 per year",
    "description": "As a Data Analyst, you'll work with large data sets to extract meaningful insights for business strategies.",
  },
  {
    "job_name": "Cloud Architect",
    "company_name": "Oracle",
    "location": "Bangalore",
    "qualification": "B.Tech in Computer Science or Cloud Computing",
    "apply_link": "https://www.oracle.com/careers",
    "salary": "₹20,00,000 per year",
    "description": "Design and implement scalable cloud solutions for enterprise clients at Oracle.",
  },
  {
    "job_name": "SAP Consultant",
    "company_name": "Capgemini",
    "location": "Mumbai",
    "qualification": "B.Tech in IT or related fields, SAP Certification",
    "apply_link": "https://www.capgemini.com/careers",
    "salary": "₹9,50,000 per year",
    "description": "Provide SAP solutions to clients, optimizing business processes using SAP modules.",
  },
  {
    "job_name": "Blockchain Developer",
    "company_name": "Wipro",
    "location": "Bangalore",
    "qualification": "B.Tech in Computer Science, Blockchain Certification",
    "apply_link": "https://www.wipro.com/careers",
    "salary": "₹12,00,000 per year",
    "description": "Develop and implement blockchain-based applications to revolutionize digital transactions.",
  },
  {
    "job_name": "UI/UX Developer",
    "company_name": "HCL Technologies",
    "location": "Chennai",
    "qualification": "B.Des/B.Tech in Design or Computer Science",
    "apply_link": "https://www.hcltech.com/careers",
    "salary": "₹8,00,000 per year",
    "description": "Design user interfaces that are intuitive and responsive, ensuring a seamless user experience.",
  },
  {
    "job_name": "System Administrator",
    "company_name": "IBM",
    "location": "Hyderabad",
    "qualification": "B.Tech in Computer Science or related field",
    "apply_link": "https://www.ibm.com/careers",
    "salary": "₹7,00,000 per year",
    "description": "Ensure smooth operation and management of system servers, network configurations, and troubleshoot technical issues.",
  },
  {
    "job_name": "Network Security Engineer",
    "company_name": "Cisco",
    "location": "Pune",
    "qualification": "B.Tech in Networking or IT",
    "apply_link": "https://www.cisco.com/careers",
    "salary": "₹11,00,000 per year",
    "description": "Cisco is hiring a network security engineer to safeguard company systems and networks from external and internal threats.",
  },
  {
    "job_name": "SEO Specialist",
    "company_name": "Zoho",
    "location": "Chennai",
    "qualification": "Bachelor's degree in Marketing, IT or related field",
    "apply_link": "https://www.zoho.com/careers",
    "salary": "₹5,50,000 per year",
    "description": "Optimize content to rank higher in search engines and drive traffic to Zoho's digital platforms.",
  },
  {
    "job_name": "Software Test Engineer",
    "company_name": "Mindtree",
    "location": "Bangalore",
    "qualification": "B.Tech in Computer Science",
    "apply_link": "https://www.mindtree.com/careers",
    "salary": "₹7,50,000 per year",
    "description": "Responsible for ensuring the quality of software products by testing applications for bugs and performance issues.",
  },
  {
    "job_name": "Database Administrator",
    "company_name": "Accenture",
    "location": "Hyderabad",
    "qualification": "B.Tech in IT, Database Management",
    "apply_link": "https://www.accenture.com/careers",
    "salary": "₹9,00,000 per year",
    "description": "Manage and secure databases, ensuring optimal performance and data integrity.",
  },
  {
    "job_name": "Software Development Engineer",
    "company_name": "SAP",
    "location": "Bangalore",
    "qualification": "B.Tech in Computer Science or related fields",
    "apply_link": "https://www.sap.com/careers",
    "salary": "₹14,00,000 per year",
    "description": "Develop scalable software solutions for SAP’s enterprise clients, enhancing their business processes.",
  },
  {
    "job_name": "QA Automation Engineer",
    "company_name": "Tech Mahindra",
    "location": "Mumbai",
    "qualification": "B.Tech in Computer Science",
    "apply_link": "https://www.techmahindra.com/careers",
    "salary": "₹8,50,000 per year",
    "description": "Develop automated test scripts and manage quality assurance processes for software applications.",
  },
  {
    "job_name": "Digital Transformation Consultant",
    "company_name": "Cognizant",
    "location": "Chennai",
    "qualification": "MBA, B.Tech in Computer Science",
    "apply_link": "https://www.cognizant.com/careers",
    "salary": "₹15,00,000 per year",
    "description": "Consult with clients on how to optimize and automate business processes for better performance and efficiency.",
  },
  {
    "job_name": "Machine Learning Engineer",
    "company_name": "Infosys",
    "location": "Bangalore",
    "qualification": "B.Tech/M.Tech in Computer Science, AI, or Data Science",
    "apply_link": "https://www.infosys.com/careers",
    "salary": "₹13,00,000 per year",
    "description": "Develop machine learning algorithms and models to enhance business intelligence and decision-making.",
  },
  {
    "job_name": "Solutions Architect",
    "company_name": "Amazon Web Services",
    "location": "Hyderabad",
    "qualification": "B.Tech in Computer Science or IT",
    "apply_link": "https://aws.amazon.com/careers",
    "salary": "₹22,00,000 per year",
    "description": "Design and implement cloud-based solutions for enterprise clients using AWS services.",
  },
  {
    "job_name": "Product Manager",
    "company_name": "Flipkart",
    "location": "Bangalore",
    "qualification": "MBA or equivalent",
    "apply_link": "https://www.flipkart.com/careers",
    "salary": "₹16,00,000 per year",
    "description": "Product Manager to oversee the development and growth of key product lines at Flipkart.",
  },
  {
    "job_name": "HR Manager",
    "company_name": "Tata Consultancy Services",
    "location": "Mumbai",
    "qualification": "MBA in HR or related field",
    "apply_link": "https://www.tcs.com/careers",
    "salary": "₹12,00,000 per year",
    "description": "Manage recruitment, employee relations, and ensure smooth HR operations within the company.",
  },
  {
    "job_name": "Business Analyst",
    "company_name": "Wipro",
    "location": "Chennai",
    "qualification": "B.Tech/MBA",
    "apply_link": "https://www.wipro.com/careers",
    "salary": "₹8,50,000 per year",
    "description": "Gather and analyze business requirements to help improve processes and performance.",
  },
  {
    "job_name": "Salesforce Developer",
    "company_name": "Cognizant",
    "location": "Hyderabad",
    "qualification": "B.Tech/M.Tech in Computer Science",
    "apply_link": "https://www.cognizant.com/careers",
    "salary": "₹11,00,000 per year",
    "description": "Develop and manage Salesforce applications to enhance business capabilities.",
  },
  {
    "job_name": "IT Support Engineer",
    "company_name": "Infosys",
    "location": "Pune",
    "qualification": "B.Tech in IT or related field",
    "apply_link": "https://www.infosys.com/careers",
    "salary": "₹5,50,000 per year",
    "description": "Provide IT support and resolve technical issues for employees and clients.",
  },
  {
    "job_name": "Data Scientist",
    "company_name": "IBM",
    "location": "Bangalore",
    "qualification": "M.Sc./M.Tech in Data Science, AI",
    "apply_link": "https://www.ibm.com/careers",
    "salary": "₹14,00,000 per year",
    "description": "Apply machine learning algorithms and statistical methods to large data sets to solve complex business problems.",
  },
  {
    "job_name": "Cloud Engineer",
    "company_name": "Amazon Web Services",
    "location": "Hyderabad",
    "qualification": "B.Tech in Cloud Computing",
    "apply_link": "https://aws.amazon.com/careers",
    "salary": "₹15,00,000 per year",
    "description": "Design and manage scalable cloud infrastructure solutions for clients.",
  },
  {
    "job_name": "Full Stack Developer",
    "company_name": "Accenture",
    "location": "Bangalore",
    "qualification": "B.Tech in Computer Science",
    "apply_link": "https://www.accenture.com/careers",
    "salary": "₹9,50,000 per year",
    "description": "Develop both front-end and back-end systems for large scale web applications.",
  },
  {
    "job_name": "Graphic Designer",
    "company_name": "Adobe",
    "location": "Noida",
    "qualification": "Bachelor’s in Design or related field",
    "apply_link": "https://www.adobe.com/careers",
    "salary": "₹7,00,000 per year",
    "description": "Create visually appealing designs for digital and print marketing materials.",
  },
  {
    "job_name": "SEO Manager",
    "company_name": "Zoho",
    "location": "Chennai",
    "qualification": "Bachelor’s degree in Marketing or related field",
    "apply_link": "https://www.zoho.com/careers",
    "salary": "₹9,00,000 per year",
    "description": "Develop and implement SEO strategies to improve website rankings and user traffic.",
  },
  {
    "job_name": "Content Writer",
    "company_name": "HCL Technologies",
    "location": "Bangalore",
    "qualification": "Bachelor's degree in English, Communications, or similar",
    "apply_link": "https://www.hcltech.com/careers",
    "salary": "₹6,00,000 per year",
    "description": "Write and edit content for blogs, websites, social media, and marketing campaigns.",
  },
  {
    "job_name": "Blockchain Engineer",
    "company_name": "Tech Mahindra",
    "location": "Hyderabad",
    "qualification": "B.Tech in Computer Science",
    "apply_link": "https://www.techmahindra.com/careers",
    "salary": "₹12,50,000 per year",
    "description": "Develop blockchain-based applications and solutions for various industries.",
  },
  {
    "job_name": "Digital Marketing Manager",
    "company_name": "Bajaj Finserv",
    "location": "Pune",
    "qualification": "MBA in Marketing or relevant field",
    "apply_link": "https://www.bajajfinserv.in/careers",
    "salary": "₹10,00,000 per year",
    "description": "Drive online marketing strategies for products and services in the digital space.",
  },
  {
    "job_name": "Backend Developer",
    "company_name": "Paytm",
    "location": "Noida",
    "qualification": "B.Tech in Computer Science",
    "apply_link": "https://www.paytm.com/careers",
    "salary": "₹9,50,000 per year",
    "description": "Build and maintain the back-end of applications, working with databases and server-side logic.",
  },
  {
    "job_name": "Business Development Manager",
    "company_name": "Capgemini",
    "location": "Mumbai",
    "qualification": "MBA in Business Development or Marketing",
    "apply_link": "https://www.capgemini.com/careers",
    "salary": "₹11,00,000 per year",
    "description": "Drive new business opportunities and client relationships to increase revenue.",
  },
  {
    "job_name": "Mobile App Developer",
    "company_name": "Cognizant",
    "location": "Chennai",
    "qualification": "B.Tech in Computer Science",
    "apply_link": "https://www.cognizant.com/careers",
    "salary": "₹10,50,000 per year",
    "description": "Develop mobile applications for Android/iOS platforms for various clients.",
  },
  {
    "job_name": "Network Engineer",
    "company_name": "Wipro",
    "location": "Hyderabad",
    "qualification": "B.Tech in Networking or IT",
    "apply_link": "https://www.wipro.com/careers",
    "salary": "₹8,00,000 per year",
    "description": "Maintain and troubleshoot the network infrastructure, ensuring minimal downtime and optimal performance.",
  },
  {
    "job_name": "Site Reliability Engineer",
    "company_name": "Google",
    "location": "Bangalore",
    "qualification": "B.Tech in Computer Science",
    "apply_link": "https://careers.google.com",
    "salary": "₹15,00,000 per year",
    "description": "Ensure the availability and reliability of systems and services across Google’s infrastructure.",
  },
  {
    "job_name": "Marketing Analyst",
    "company_name": "HDFC Bank",
    "location": "Mumbai",
    "qualification": "B.Tech or MBA in Marketing",
    "apply_link": "https://www.hdfcbank.com/careers",
    "salary": "₹7,50,000 per year",
    "description": "Analyze market trends and customer data to create effective marketing campaigns.",
  },
  {
    "job_name": "Sales Executive",
    "company_name": "Reliance Industries",
    "location": "Mumbai",
    "qualification": "MBA in Sales/Marketing",
    "apply_link": "https://www.relianceindustries.com/careers",
    "salary": "₹6,00,000 per year",
    "description": "Generate leads and manage customer relationships to increase product sales.",
  },
  {
    "job_title": "Software Developer",
    "company": "Accenture",
    "location": "Bangalore",
    "skills_required": ["Java", "Python", "C++"],
    "experience_level": "Fresher",
    "apply_link": "https://www.accenture.com/in-en/careers"
  },
  {
    "job_title": "Data Analyst",
    "company": "TCS",
    "location": "Mumbai",
    "skills_required": ["Excel", "SQL", "Python"],
    "experience_level": "2+ years",
    "apply_link": "https://www.tcs.com/careers"
  },
  {
    "job_title": "Project Manager",
    "company": "Cognizant",
    "location": "Chennai",
    "skills_required": ["Agile", "Scrum", "Project Management"],
    "experience_level": "5+ years",
    "apply_link": "https://careers.cognizant.com/"
  },
  {
    "job_title": "UI/UX Designer",
    "company": "IBM",
    "location": "Pune",
    "skills_required": ["Figma", "Sketch", "Wireframing"],
    "experience_level": "2+ years",
    "apply_link": "https://www.ibm.com/employment/"
  },
  {
    "job_title": "Full Stack Developer",
    "company": "HCLTech",
    "location": "Hyderabad",
    "skills_required": ["JavaScript", "React", "Node.js"],
    "experience_level": "3+ years",
    "apply_link": "https://www.hcltech.com/careers"
  },
  {
    "job_title": "Sales Executive",
    "company": "Samsung",
    "location": "Delhi",
    "skills_required": ["Sales", "Marketing"],
    "experience_level": "1-3 years",
    "apply_link": "https://www.samsung.com/in/about-us/careers/"
  },
  {
    "job_title": "HR Manager",
    "company": "Wipro",
    "location": "Bangalore",
    "skills_required": ["HRM", "Recruitment"],
    "experience_level": "4+ years",
    "apply_link": "https://careers.wipro.com/"
  },
  {
    "job_title": "Content Writer",
    "company": "Zoho",
    "location": "Chennai",
    "skills_required": ["Content Writing", "SEO"],
    "experience_level": "1-2 years",
    "apply_link": "https://www.zoho.com/careers/"
  },
  {
    "job_title": "Finance Analyst",
    "company": "J.P. Morgan",
    "location": "Mumbai",
    "skills_required": ["Finance", "Excel", "SAP"],
    "experience_level": "2+ years",
    "apply_link": "https://www.jpmorgan.com/careers"
  },
  {
    "job_title": "Customer Service Representative",
    "company": "American Express",
    "location": "Noida",
    "skills_required": ["Customer Support", "Communication"],
    "experience_level": "1+ years",
    "apply_link": "https://www.americanexpress.com/en-in/careers/"
  },
  {
    "job_title": "Business Development Executive",
    "company": "LinkedIn",
    "location": "Mumbai",
    "skills_required": ["Sales", "Negotiation"],
    "experience_level": "1-3 years",
    "apply_link": "https://careers.linkedin.com/"
  },
  {
    "job_title": "Machine Learning Engineer",
    "company": "Capgemini",
    "location": "Pune",
    "skills_required": ["Python", "TensorFlow", "Machine Learning"],
    "experience_level": "3+ years",
    "apply_link": "https://www.capgemini.com/careers/"
  },
  {
    "job_title": "Graphic Designer",
    "company": "Adobe",
    "location": "Bangalore",
    "skills_required": ["Photoshop", "Illustrator", "Creative Suite"],
    "experience_level": "2+ years",
    "apply_link": "https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced"
  },
  {
    "job_title": "Digital Marketing Specialist",
    "company": "Google",
    "location": "Hyderabad",
    "skills_required": ["SEO", "PPC", "Content Marketing"],
    "experience_level": "2+ years",
    "apply_link": "https://careers.google.com/"
  },
  {
    "job_title": "Business Analyst",
    "company": "Deloitte",
    "location": "Bangalore",
    "skills_required": ["SQL", "Business Intelligence"],
    "experience_level": "3+ years",
    "apply_link": "https://www2.deloitte.com/in/en/careers.html"
  },
  {
    "job_title": "Network Engineer",
    "company": "Cisco",
    "location": "Mumbai",
    "skills_required": ["Networking", "Cisco Certifications"],
    "experience_level": "2+ years",
    "apply_link": "https://www.cisco.com/c/en/us/about/careers.html"
  },
  {
    "job_title": "Operations Manager",
    "company": "Flipkart",
    "location": "Bangalore",
    "skills_required": ["Operations", "Logistics"],
    "experience_level": "5+ years",
    "apply_link": "https://www.flipkart.com/jobs"
  },
  {
    "job_title": "Cybersecurity Analyst",
    "company": "PwC",
    "location": "Delhi",
    "skills_required": ["Cybersecurity", "Risk Management"],
    "experience_level": "3+ years",
    "apply_link": "https://www.pwc.in/careers.html"
  },
  {
    "job_title": "Product Manager",
    "company": "Paytm",
    "location": "Noida",
    "skills_required": ["Product Management", "Agile"],
    "experience_level": "4+ years",
    "apply_link": "https://paytm.com/careers"
  },
  {
    "job_title": "Social Media Manager",
    "company": "Snapdeal",
    "location": "Gurgaon",
    "skills_required": ["Social Media Marketing", "Content Creation"],
    "experience_level": "2+ years",
    "apply_link": "https://www.snapdeal.com/jobs"
  },
  {
    "job_title": "Backend Developer",
    "company": "Tech Mahindra",
    "location": "Pune",
    "skills_required": ["Java", "Spring Boot", "Microservices"],
    "experience_level": "3+ years",
    "apply_link": "https://www.techmahindra.com/careers"
  },
  {
    "job_title": "Marketing Manager",
    "company": "Zomato",
    "location": "Delhi",
    "skills_required": ["SEO", "Content Strategy", "Branding"],
    "experience_level": "5+ years",
    "apply_link": "https://www.zomato.com/careers"
  },
  {
    "job_title": "Frontend Developer",
    "company": "Wipro",
    "location": "Chennai",
    "skills_required": ["React", "JavaScript", "CSS"],
    "experience_level": "2+ years",
    "apply_link": "https://careers.wipro.com/"
  },
  {
    "job_title": "Accountant",
    "company": "KPMG",
    "location": "Mumbai",
    "skills_required": ["Accounting", "Taxation", "Excel"],
    "experience_level": "2+ years",
    "apply_link": "https://home.kpmg/in/en/home/careers.html"
  },
  {
    "job_title": "Android Developer",
    "company": "Cure.fit",
    "location": "Bangalore",
    "skills_required": ["Java", "Kotlin", "Android Studio"],
    "experience_level": "2+ years",
    "apply_link": "https://www.curefit.com/careers"
  },
  {
    "job_title": "DevOps Engineer",
    "company": "Amazon",
    "location": "Hyderabad",
    "skills_required": ["AWS", "Docker", "CI/CD"],
    "experience_level": "3+ years",
    "apply_link": "https://www.amazon.jobs/en/"
  },
  {
    "job_title": "Product Designer",
    "company": "Razorpay",
    "location": "Bangalore",
    "skills_required": ["Figma", "User Interface Design"],
    "experience_level": "2+ years",
    "apply_link": "https://razorpay.com/careers/"
  },
  {
    "job_title": "Business Analyst",
    "company": "Accenture",
    "location": "Gurgaon",
    "skills_required": ["Business Intelligence", "SQL", "Data Analysis"],
    "experience_level": "2+ years",
    "apply_link": "https://www.accenture.com/in-en/careers"
  },
  {
    "job_title": "Machine Learning Engineer",
    "company": "Adobe",
    "location": "Bangalore",
    "skills_required": ["Python", "TensorFlow", "Deep Learning"],
    "experience_level": "3+ years",
    "apply_link": "https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced"
  },
  {
    "job_title": "Customer Support Specialist",
    "company": "Freshworks",
    "location": "Chennai",
    "skills_required": ["Customer Support", "CRM"],
    "experience_level": "1-2 years",
    "apply_link": "https://www.freshworks.com/careers/"
  },
  {
    "job_title": "Salesforce Developer",
    "company": "Cognizant",
    "location": "Kolkata",
    "skills_required": ["Salesforce", "Apex", "Visualforce"],
    "experience_level": "2+ years",
    "apply_link": "https://careers.cognizant.com/"
  },
  {
    "job_title": "Cloud Engineer",
    "company": "Oracle",
    "location": "Hyderabad",
    "skills_required": ["Cloud Computing", "AWS", "Azure"],
    "experience_level": "3+ years",
    "apply_link": "https://www.oracle.com/corporate/careers/"
  },
  {
    "job_title": "HR Specialist",
    "company": "HCLTech",
    "location": "Chennai",
    "skills_required": ["Human Resources", "Recruitment", "Onboarding"],
    "experience_level": "2+ years",
    "apply_link": "https://www.hcltech.com/careers"
  },
  {
    "job_title": "Full Stack Engineer",
    "company": "LinkedIn",
    "location": "Mumbai",
    "skills_required": ["Node.js", "React", "MongoDB"],
    "experience_level": "3+ years",
    "apply_link": "https://careers.linkedin.com/"
  },
  {
    "job_title": "IT Support Specialist",
    "company": "IBM",
    "location": "Pune",
    "skills_required": ["IT Support", "Networking", "Windows Server"],
    "experience_level": "1+ years",
    "apply_link": "https://www.ibm.com/employment/"
  },
  {
    "job_title": "Finance Manager",
    "company": "PwC",
    "location": "Delhi",
    "skills_required": ["Accounting", "Taxation", "Financial Reporting"],
    "experience_level": "5+ years",
    "apply_link": "https://www.pwc.in/careers.html"
  },
  {
    "job_title": "Operations Executive",
    "company": "Flipkart",
    "location": "Bangalore",
    "skills_required": ["Logistics", "Operations Management"],
    "experience_level": "2+ years",
    "apply_link": "https://www.flipkart.com/jobs"
  },
  {
    "job_title": "Data Scientist",
    "company": "Zycus",
    "location": "Mumbai",
    "skills_required": ["Python", "Machine Learning", "Big Data"],
    "experience_level": "3+ years",
    "apply_link": "https://www.zycus.com/careers.html"
  },
  {
    "job_title": "Java Developer",
    "company": "TCS",
    "location": "Hyderabad",
    "skills_required": ["Java", "Spring", "Hibernate"],
    "experience_level": "2+ years",
    "apply_link": "https://www.tcs.com/careers"
  },
  {
    "job_title": "Content Strategist",
    "company": "Byju’s",
    "location": "Bangalore",
    "skills_required": ["Content Creation", "SEO", "Copywriting"],
    "experience_level": "3+ years",
    "apply_link": "https://byjus.com/careers/"
  },
  {
    "job_title": "Backend Engineer",
    "company": "Urban Company",
    "location": "Delhi",
    "skills_required": ["Node.js", "Express", "MongoDB"],
    "experience_level": "2+ years",
    "apply_link": "https://www.urbancompany.com/careers"
  },
  {
    "job_title": "Legal Counsel",
    "company": "Flipkart",
    "location": "Bangalore",
    "skills_required": ["Legal Research", "Contract Law"],
    "experience_level": "4+ years",
    "apply_link": "https://www.flipkart.com/jobs"
  },
  {
    "job_title": "Technical Writer",
    "company": "Zoho",
    "location": "Chennai",
    "skills_required": ["Technical Writing", "Documentation", "MS Office"],
    "experience_level": "2+ years",
    "apply_link": "https://www.zoho.com/careers/"
  },
  {
    "job_title": "Cybersecurity Consultant",
    "company": "Accenture",
    "location": "Delhi",
    "skills_required": ["Cybersecurity", "Risk Management"],
    "experience_level": "3+ years",
    "apply_link": "https://www.accenture.com/in-en/careers"
  },
  {
    "job_title": "Web Developer",
    "company": "Mindtree",
    "location": "Chennai",
    "skills_required": ["HTML", "CSS", "JavaScript"],
    "experience_level": "1+ years",
    "apply_link": "https://www.mindtree.com/careers"
  },
  {
    "job_title": "HR Manager",
    "company": "Cognizant",
    "location": "Hyderabad",
    "skills_required": ["HR Management", "Employee Relations"],
    "experience_level": "5+ years",
    "apply_link": "https://careers.cognizant.com/"
  },
  {
    "job_title": "Sales Manager",
    "company": "Salesforce",
    "location": "Mumbai",
    "skills_required": ["Sales", "CRM", "Team Leadership"],
    "experience_level": "5+ years",
    "apply_link": "https://www.salesforce.com/company/careers/"
  },
  {
    "job_title": "Digital Marketing Executive",
    "company": "Naukri.com",
    "location": "Noida",
    "skills_required": ["Digital Marketing", "SEO", "Social Media"],
    "experience_level": "1-3 years",
    "apply_link": "https://www.naukri.com/careers"
  },

  {
    "job_title": "Backend Developer",
    "company": "Tech Mahindra",
    "location": "Pune",
    "skills_required": ["Java", "Spring Boot", "Microservices"],
    "experience_level": "3+ years",
    "apply_link": "https://www.techmahindra.com/careers"
  },
  {
    "job_title": "Marketing Manager",
    "company": "Zomato",
    "location": "Delhi",
    "skills_required": ["SEO", "Content Strategy", "Branding"],
    "experience_level": "5+ years",
    "apply_link": "https://www.zomato.com/careers"
  },
  {
    "job_title": "Frontend Developer",
    "company": "Wipro",
    "location": "Chennai",
    "skills_required": ["React", "JavaScript", "CSS"],
    "experience_level": "2+ years",
    "apply_link": "https://careers.wipro.com/"
  },
  {
    "job_title": "Accountant",
    "company": "KPMG",
    "location": "Mumbai",
    "skills_required": ["Accounting", "Taxation", "Excel"],
    "experience_level": "2+ years",
    "apply_link": "https://home.kpmg/in/en/home/careers.html"
  },
  {
    "job_title": "Android Developer",
    "company": "Cure.fit",
    "location": "Bangalore",
    "skills_required": ["Java", "Kotlin", "Android Studio"],
    "experience_level": "2+ years",
    "apply_link": "https://www.curefit.com/careers"
  },
  {
    "job_title": "DevOps Engineer",
    "company": "Amazon",
    "location": "Hyderabad",
    "skills_required": ["AWS", "Docker", "CI/CD"],
    "experience_level": "3+ years",
    "apply_link": "https://www.amazon.jobs/en/"
  },
  {
    "job_title": "Product Designer",
    "company": "Razorpay",
    "location": "Bangalore",
    "skills_required": ["Figma", "User Interface Design"],
    "experience_level": "2+ years",
    "apply_link": "https://razorpay.com/careers/"
  },
  {
    "job_title": "Business Analyst",
    "company": "Accenture",
    "location": "Gurgaon",
    "skills_required": ["Business Intelligence", "SQL", "Data Analysis"],
    "experience_level": "2+ years",
    "apply_link": "https://www.accenture.com/in-en/careers"
  },
  {
    "job_title": "Machine Learning Engineer",
    "company": "Adobe",
    "location": "Bangalore",
    "skills_required": ["Python", "TensorFlow", "Deep Learning"],
    "experience_level": "3+ years",
    "apply_link": "https://adobe.wd5.myworkdayjobs.com/en-US/external_experienced"
  },
  {
    "job_title": "Customer Support Specialist",
    "company": "Freshworks",
    "location": "Chennai",
    "skills_required": ["Customer Support", "CRM"],
    "experience_level": "1-2 years",
    "apply_link": "https://www.freshworks.com/careers/"
  },
  {
    "job_title": "Salesforce Developer",
    "company": "Cognizant",
    "location": "Kolkata",
    "skills_required": ["Salesforce", "Apex", "Visualforce"],
    "experience_level": "2+ years",
    "apply_link": "https://careers.cognizant.com/"
  },
  {
    "job_title": "Cloud Engineer",
    "company": "Oracle",
    "location": "Hyderabad",
    "skills_required": ["Cloud Computing", "AWS", "Azure"],
    "experience_level": "3+ years",
    "apply_link": "https://www.oracle.com/corporate/careers/"
  },
  {
    "job_title": "HR Specialist",
    "company": "HCLTech",
    "location": "Chennai",
    "skills_required": ["Human Resources", "Recruitment", "Onboarding"],
    "experience_level": "2+ years",
    "apply_link": "https://www.hcltech.com/careers"
  },
  {
    "job_title": "Full Stack Engineer",
    "company": "LinkedIn",
    "location": "Mumbai",
    "skills_required": ["Node.js", "React", "MongoDB"],
    "experience_level": "3+ years",
    "apply_link": "https://careers.linkedin.com/"
  },
  {
    "job_title": "IT Support Specialist",
    "company": "IBM",
    "location": "Pune",
    "skills_required": ["IT Support", "Networking", "Windows Server"],
    "experience_level": "1+ years",
    "apply_link": "https://www.ibm.com/employment/"
  },
  {
    "job_title": "Finance Manager",
    "company": "PwC",
    "location": "Delhi",
    "skills_required": ["Accounting", "Taxation", "Financial Reporting"],
    "experience_level": "5+ years",
    "apply_link": "https://www.pwc.in/careers.html"
  },
  {
    "job_title": "Operations Executive",
    "company": "Flipkart",
    "location": "Bangalore",
    "skills_required": ["Logistics", "Operations Management"],
    "experience_level": "2+ years",
    "apply_link": "https://www.flipkart.com/jobs"
  },
  {
    "job_title": "Data Scientist",
    "company": "Zycus",
    "location": "Mumbai",
    "skills_required": ["Python", "Machine Learning", "Big Data"],
    "experience_level": "3+ years",
    "apply_link": "https://www.zycus.com/careers.html"
  },
  {
    "job_title": "Java Developer",
    "company": "TCS",
    "location": "Hyderabad",
    "skills_required": ["Java", "Spring", "Hibernate"],
    "experience_level": "2+ years",
    "apply_link": "https://www.tcs.com/careers"
  },
  {
    "job_title": "Content Strategist",
    "company": "Byju’s",
    "location": "Bangalore",
    "skills_required": ["Content Creation", "SEO", "Copywriting"],
    "experience_level": "3+ years",
    "apply_link": "https://byjus.com/careers/"
  },
  {
    "job_title": "Backend Engineer",
    "company": "Urban Company",
    "location": "Delhi",
    "skills_required": ["Node.js", "Express", "MongoDB"],
    "experience_level": "2+ years",
    "apply_link": "https://www.urbancompany.com/careers"
  },
  {
    "job_title": "Legal Counsel",
    "company": "Flipkart",
    "location": "Bangalore",
    "skills_required": ["Legal Research", "Contract Law"],
    "experience_level": "4+ years",
    "apply_link": "https://www.flipkart.com/jobs"
  },
  {
    "job_title": "Technical Writer",
    "company": "Zoho",
    "location": "Chennai",
    "skills_required": ["Technical Writing", "Documentation", "MS Office"],
    "experience_level": "2+ years",
    "apply_link": "https://www.zoho.com/careers/"
  },
  {
    "job_title": "Cybersecurity Consultant",
    "company": "Accenture",
    "location": "Delhi",
    "skills_required": ["Cybersecurity", "Risk Management"],
    "experience_level": "3+ years",
    "apply_link": "https://www.accenture.com/in-en/careers"
  },
  {
    "job_title": "Web Developer",
    "company": "Mindtree",
    "location": "Chennai",
    "skills_required": ["HTML", "CSS", "JavaScript"],
    "experience_level": "1+ years",
    "apply_link": "https://www.mindtree.com/careers"
  },
  {
    "job_title": "HR Manager",
    "company": "Cognizant",
    "location": "Hyderabad",
    "skills_required": ["HR Management", "Employee Relations"],
    "experience_level": "5+ years",
    "apply_link": "https://careers.cognizant.com/"
  },
  {
    "job_title": "Sales Manager",
    "company": "Salesforce",
    "location": "Mumbai",
    "skills_required": ["Sales", "CRM", "Team Leadership"],
    "experience_level": "5+ years",
    "apply_link": "https://www.salesforce.com/company/careers/"
  },
  {
    "job_title": "Digital Marketing Executive",
    "company": "Naukri.com",
    "location": "Noida",
    "skills_required": ["Digital Marketing", "SEO", "Social Media"],
    "experience_level": "1-3 years",
    "apply_link": "https://www.naukri.com/careers"
  },
  {
    "job_title": "Data Scientist, Product (Marketplace)",
    "salary_range": "$140k – $182k",
    "location": "Remote, USA",
    "company_name": "Blue River Technology",
    "job_link": "https://wellfound.com/jobs/123456",
    "qualification": "PhD or Master's in Data Science or similar field",
    "description": "Designing AI-driven solutions for smart agriculture equipment."
  },
  {
    "job_title": "Principal SLAM Engineer",
    "salary_range": "$142k – $293k",
    "location": "Remote, Santa Clara",
    "company_name": "River",
    "job_link": "https://wellfound.com/jobs/123457",
    "qualification": "PhD or MS in Robotics, Computer Science, or related field",
    "description": "Developing cutting-edge SLAM algorithms for autonomous vehicles."
  },
  {
    "job_title": "Sr. Software Engineer, Data Platform",
    "salary_range": "$142k – $250k",
    "location": "Remote, Santa Clara",
    "company_name": "River",
    "job_link": "https://wellfound.com/jobs/123458",
    "qualification": "BS/MS in Computer Science or related discipline",
    "description": "Building scalable data platforms to power AI applications."
  },
  {
    "job_title": "Senior Software Engineer",
    "salary_range": "$150k – $220k",
    "location": "Remote",
    "company_name": "Thyme Care",
    "job_link": "https://wellfound.com/jobs/123459",
    "qualification": "Experience with backend technologies and cloud infrastructure",
    "description": "Designing and building software solutions for healthcare management."
  },
  {
    "job_title": "Senior Platform Engineer",
    "salary_range": "$160k – $190k",
    "location": "Remote",
    "company_name": "Thyme Care",
    "job_link": "https://wellfound.com/jobs/123460",
    "qualification": "Cloud experience, microservices architecture expertise",
    "description": "Developing the platform for healthcare analytics and patient management."
  },
  {
    "job_title": "Sr. Frontend Engineer",
    "salary_range": "$150k – $160k",
    "location": "Remote",
    "company_name": "dv01",
    "job_link": "https://wellfound.com/jobs/123461",
    "qualification": "Expertise in JavaScript, React, and web development",
    "description": "Creating intuitive front-end interfaces for financial data platforms."
  },
  {
    "job_title": "Quantitative Engineer II",
    "salary_range": "$135k – $150k",
    "location": "Remote",
    "company_name": "dv01",
    "job_link": "https://wellfound.com/jobs/123462",
    "qualification": "Degree in quantitative field, proficiency in Python or R",
    "description": "Building algorithms for financial data analysis and predictions."
  },
  {
    "job_title": "Full-Stack Software Engineer, Adoption",
    "salary_range": "$122k – $158k",
    "location": "Remote",
    "company_name": "Virta Health",
    "job_link": "https://wellfound.com/jobs/123463",
    "qualification": "Full-stack development experience, proficiency in Node.js, React",
    "description": "Developing software solutions for healthcare service adoption."
  },
  {
    "job_title": "Senior Data Scientist",
    "salary_range": "$164k – $213k",
    "location": "Remote",
    "company_name": "Virta Health",
    "job_link": "https://wellfound.com/jobs/123464",
    "qualification": "Data science, machine learning expertise, advanced degree preferred",
    "description": "Analyzing healthcare data to improve patient care through AI."
  },
  {
    "job_title": "Senior Health Economics and Outcomes Research Scientist",
    "salary_range": "$183k – $217k",
    "location": "Remote",
    "company_name": "Virta Health",
    "job_link": "https://wellfound.com/jobs/123465",
    "qualification": "PhD in health economics or similar field",
    "description": "Driving research to improve health outcomes and cost effectiveness."
  },
  {
    "job_title": "Senior Network Engineer",
    "salary_range": "$133k – $185k",
    "location": "Remote, USA",
    "company_name": "Upstart",
    "job_link": "https://wellfound.com/jobs/123466",
    "qualification": "Experience with cloud networks and infrastructure",
    "description": "Designing and optimizing network systems for financial technology."
  },
  {
    "job_title": "Distinguished Engineer, Underwriting Platform",
    "salary_range": "$213k – $295k",
    "location": "Remote, USA",
    "company_name": "Upstart",
    "job_link": "https://wellfound.com/jobs/123467",
    "qualification": "Expert in underwriting systems, cloud computing, and microservices",
    "description": "Building scalable underwriting platforms for financial products."
  },
  {
    "job_title": "Senior Product Manager, Servicing",
    "salary_range": "$162k – $225k",
    "location": "Remote, USA",
    "company_name": "Upstart",
    "job_link": "https://wellfound.com/jobs/123468",
    "qualification": "Product management experience, financial services knowledge",
    "description": "Leading product development for servicing platforms in fintech."
  },
  {
    "job_title": "Software Engineer, Full Stack",
    "salary_range": "$150k – $230k",
    "location": "Hybrid (San Francisco/Toronto)",
    "company_name": "Magical",
    "job_link": "https://wellfound.com/jobs/123469",
    "qualification": "Full-stack development experience, JavaScript, React, Node.js",
    "description": "Building tools for enhancing productivity in the remote workspace."
  },
  {
    "job_title": "Full Stack Developer",
    "salary_range": "$120k – $180k",
    "location": "Remote",
    "company_name": "Ramp",
    "job_link": "https://wellfound.com/jobs/123470",
    "qualification": "Experience in backend and frontend development, cloud infrastructure",
    "description": "Developing cutting-edge software solutions for financial services."
  },
  {
    "job_title": "Product Manager",
    "salary_range": "$150k – $200k",
    "location": "Remote",
    "company_name": "Conflux Network",
    "job_link": "https://wellfound.com/jobs/123471",
    "qualification": "Experience in blockchain, decentralized finance, or Web3",
    "description": "Leading product development in a blockchain-based platform."
  },
  {
    "job_title": "Software Engineer (Frontend)",
    "salary_range": "$130k – $180k",
    "location": "Remote",
    "company_name": "Usable",
    "job_link": "https://wellfound.com/jobs/123472",
    "qualification": "Expertise in React.js and web development",
    "description": "Building modern frontend applications for user-centric platforms."
  },
  {
    "job_title": "AI Researcher",
    "salary_range": "$160k – $220k",
    "location": "Remote",
    "company_name": "ScholarAI",
    "job_link": "https://wellfound.com/jobs/123473",
    "qualification": "PhD or equivalent in AI research or deep learning",
    "description": "Conducting research to advance AI technologies in education."
  },
  {
    "job_title": "Mobile App Developer",
    "salary_range": "$120k – $170k",
    "location": "Remote",
    "company_name": "FarmWise",
    "job_link": "https://wellfound.com/jobs/123474",
    "qualification": "Experience in mobile app development (iOS/Android)",
    "description": "Building mobile applications for the agricultural industry."
  },
  {
    "job_title": "Senior Product Designer",
    "salary_range": "$140k – $200k",
    "location": "Remote",
    "company_name": "Quora",
    "job_link": "https://wellfound.com/jobs/123475",
    "qualification": "Experience in product design for digital platforms",
    "description": "Designing user interfaces and experiences for Quora's platform."
  }
]

export default jobs_data;